### ISSUE TITLE
Warn in console

### ISSUE THREAD

**Issue by LuuckA21** [nulli0n/NexEngine#5]
Hi, I use NexEngine and GamePoints on my server running Paper 1.16.5.
Plugin works fine, is it possible to remove this? 
![Screenshot 2021-04-11 130122](https://user-images.githubusercontent.com/50712503/114301665-31860180-9ac6-11eb-99d6-eec379840e7e.png)

**Comment by nulli0n** [comment]
It's there for a reason.

**Comment by LuuckA21** [comment]
Yes if you write there is a reason, but I hate warn in console. Plugin work perfectly on paper

**Comment by nulli0n** [comment]
Sure, but no one cares for the sames warns on spigot for example:
![6349](https://user-images.githubusercontent.com/73139339/114305584-319bf680-9af2-11eb-8394-7d37bf0e03cf.jpg)

you can remove it for yourself if you want.
