### ISSUE TITLE
UnsupportedClassVersionError

### ISSUE THREAD

**Issue by DrakMC** [nulli0n/NexEngine#9]
Hi, I'm getting this error: https://pastebin.com/raw/pb7p9uUU

**Java version:**
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment 18.9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.11+9, mixed mode, sharing)

**Comment by TheWidowsSon** [comment]
Try updating to Java 16.

**Comment by DrakMC** [comment]
It worked, thanks.
